name: 'Get prs/issues'
description: 'Get prs/issues count and output'
inputs:
  ORG_NAME:
    required: true
    description: 'organisation name'
    default: 'nest.js'
  REPO_NAME:
    required: true
    description: 'repository name'
    default: 'nest'
  AUTH_TOKEN:
    required: true
    description: 'github auth token'
  SINCE:
    description: 'since date in ISO format'
  STATE:
    description: 'state of issue/pr'
outputs:
  issues:
    description: 'amount of open issues'
  prs:
    description: 'amount of open prs'
runs:
  using: 'node16'
  main: 'dist/index.js'
