name: GH-actions-task

on:
  push:
    branches:
      - main

jobs:
  total_pr_and_issues:
    runs-on: ubuntu-latest
    env:
      ORG_NAME: "nestjs"
      REPO_NAME: "nest"
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-versions: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run start ${{ env.ORG_NAME }} ${{ env.REPO_NAME }} ${{ secrets.GITHUB_TOKEN }}
