name: GH-actions-task

on:
  push:
    branches:
      - main

jobs:
  total_pr_and_issues:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get prs/issues count
        id: node-exec
        uses: ./
        with:
          ORG_NAME: 'nestjs'
          REPO_NAME: 'nest'
          AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Display amount of prs/issues
        run: |
          echo "The total prs ${{ steps.node-exec.outputs.prs }}"
          echo "The total issues ${{ steps.node-exec.outputs.issues }}"
